/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.PermissionRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PermissionDao extends DAOImpl<PermissionRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission, UInteger> {

    /**
     * Create a new PermissionDao without any configuration
     */
    public PermissionDao() {
        super(Permission.PERMISSION, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission.class);
    }

    /**
     * Create a new PermissionDao with an attached configuration
     */
    @Autowired
    public PermissionDao(Configuration configuration) {
        super(Permission.PERMISSION, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission object) {
        return object.getPermissionId();
    }

    /**
     * Fetch records that have <code>permission_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission> fetchByPermissionId(UInteger... values) {
        return fetch(Permission.PERMISSION.PERMISSION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>permission_id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission fetchOneByPermissionId(UInteger value) {
        return fetchOne(Permission.PERMISSION.PERMISSION_ID, value);
    }

    /**
     * Fetch records that have <code>permission_name IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission> fetchByPermissionName(String... values) {
        return fetch(Permission.PERMISSION.PERMISSION_NAME, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission> fetchByCreatedTime(Timestamp... values) {
        return fetch(Permission.PERMISSION.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Permission> fetchByUpdateTime(Timestamp... values) {
        return fetch(Permission.PERMISSION.UPDATE_TIME, values);
    }
}
