/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.RoleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RoleDao extends DAOImpl<RoleRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role, UInteger> {

    /**
     * Create a new RoleDao without any configuration
     */
    public RoleDao() {
        super(Role.ROLE, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role.class);
    }

    /**
     * Create a new RoleDao with an attached configuration
     */
    @Autowired
    public RoleDao(Configuration configuration) {
        super(Role.ROLE, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role object) {
        return object.getRoleId();
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role> fetchByRoleId(UInteger... values) {
        return fetch(Role.ROLE.ROLE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>role_id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role fetchOneByRoleId(UInteger value) {
        return fetchOne(Role.ROLE.ROLE_ID, value);
    }

    /**
     * Fetch records that have <code>role_name IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role> fetchByRoleName(String... values) {
        return fetch(Role.ROLE.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role> fetchByCreatedTime(Timestamp... values) {
        return fetch(Role.ROLE.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.Role> fetchByUpdateTime(Timestamp... values) {
        return fetch(Role.ROLE.UPDATE_TIME, values);
    }
}
