/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.RolesPermissions;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.RolesPermissionsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RolesPermissionsDao extends DAOImpl<RolesPermissionsRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions, UInteger> {

    /**
     * Create a new RolesPermissionsDao without any configuration
     */
    public RolesPermissionsDao() {
        super(RolesPermissions.ROLES_PERMISSIONS, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions.class);
    }

    /**
     * Create a new RolesPermissionsDao with an attached configuration
     */
    @Autowired
    public RolesPermissionsDao(Configuration configuration) {
        super(RolesPermissions.ROLES_PERMISSIONS, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions> fetchById(UInteger... values) {
        return fetch(RolesPermissions.ROLES_PERMISSIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions fetchOneById(UInteger value) {
        return fetchOne(RolesPermissions.ROLES_PERMISSIONS.ID, value);
    }

    /**
     * Fetch records that have <code>permission_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions> fetchByPermissionId(UInteger... values) {
        return fetch(RolesPermissions.ROLES_PERMISSIONS.PERMISSION_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.RolesPermissions> fetchByRoleId(UInteger... values) {
        return fetch(RolesPermissions.ROLES_PERMISSIONS.ROLE_ID, values);
    }
}
