/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9PermissionRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class T9PermissionDao extends DAOImpl<T9PermissionRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission, UInteger> {

    /**
     * Create a new T9PermissionDao without any configuration
     */
    public T9PermissionDao() {
        super(T9Permission.T9_PERMISSION, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission.class);
    }

    /**
     * Create a new T9PermissionDao with an attached configuration
     */
    @Autowired
    public T9PermissionDao(Configuration configuration) {
        super(T9Permission.T9_PERMISSION, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission object) {
        return object.getPermissionId();
    }

    /**
     * Fetch records that have <code>permission_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission> fetchByPermissionId(UInteger... values) {
        return fetch(T9Permission.T9_PERMISSION.PERMISSION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>permission_id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission fetchOneByPermissionId(UInteger value) {
        return fetchOne(T9Permission.T9_PERMISSION.PERMISSION_ID, value);
    }

    /**
     * Fetch records that have <code>permission_name IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission> fetchByPermissionName(String... values) {
        return fetch(T9Permission.T9_PERMISSION.PERMISSION_NAME, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission> fetchByCreatedTime(Timestamp... values) {
        return fetch(T9Permission.T9_PERMISSION.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Permission> fetchByUpdateTime(Timestamp... values) {
        return fetch(T9Permission.T9_PERMISSION.UPDATE_TIME, values);
    }
}
