/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9RolePermissionRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class T9RolePermissionDao extends DAOImpl<T9RolePermissionRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission, UInteger> {

    /**
     * Create a new T9RolePermissionDao without any configuration
     */
    public T9RolePermissionDao() {
        super(T9RolePermission.T9_ROLE_PERMISSION, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission.class);
    }

    /**
     * Create a new T9RolePermissionDao with an attached configuration
     */
    @Autowired
    public T9RolePermissionDao(Configuration configuration) {
        super(T9RolePermission.T9_ROLE_PERMISSION, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission> fetchById(UInteger... values) {
        return fetch(T9RolePermission.T9_ROLE_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission fetchOneById(UInteger value) {
        return fetchOne(T9RolePermission.T9_ROLE_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>permission_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission> fetchByPermissionId(UInteger... values) {
        return fetch(T9RolePermission.T9_ROLE_PERMISSION.PERMISSION_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9RolePermission> fetchByRoleId(UInteger... values) {
        return fetch(T9RolePermission.T9_ROLE_PERMISSION.ROLE_ID, values);
    }
}
