/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9RoleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class T9RoleDao extends DAOImpl<T9RoleRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role, UInteger> {

    /**
     * Create a new T9RoleDao without any configuration
     */
    public T9RoleDao() {
        super(T9Role.T9_ROLE, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role.class);
    }

    /**
     * Create a new T9RoleDao with an attached configuration
     */
    @Autowired
    public T9RoleDao(Configuration configuration) {
        super(T9Role.T9_ROLE, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role object) {
        return object.getRoleId();
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role> fetchByRoleId(UInteger... values) {
        return fetch(T9Role.T9_ROLE.ROLE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>role_id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role fetchOneByRoleId(UInteger value) {
        return fetchOne(T9Role.T9_ROLE.ROLE_ID, value);
    }

    /**
     * Fetch records that have <code>role_name IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role> fetchByRoleName(String... values) {
        return fetch(T9Role.T9_ROLE.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role> fetchByCreatedTime(Timestamp... values) {
        return fetch(T9Role.T9_ROLE.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9Role> fetchByUpdateTime(Timestamp... values) {
        return fetch(T9Role.T9_ROLE.UPDATE_TIME, values);
    }
}
