/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9UserRole;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9UserRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class T9UserRoleDao extends DAOImpl<T9UserRoleRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole, UInteger> {

    /**
     * Create a new T9UserRoleDao without any configuration
     */
    public T9UserRoleDao() {
        super(T9UserRole.T9_USER_ROLE, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole.class);
    }

    /**
     * Create a new T9UserRoleDao with an attached configuration
     */
    @Autowired
    public T9UserRoleDao(Configuration configuration) {
        super(T9UserRole.T9_USER_ROLE, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole> fetchById(UInteger... values) {
        return fetch(T9UserRole.T9_USER_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole fetchOneById(UInteger value) {
        return fetchOne(T9UserRole.T9_USER_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole> fetchByUserId(UInteger... values) {
        return fetch(T9UserRole.T9_USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.T9UserRole> fetchByRoleId(UInteger... values) {
        return fetch(T9UserRole.T9_USER_ROLE.ROLE_ID, values);
    }
}
