/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.daos;


import com.torres999.sprintboot.shiro.dao.jooq.tables.UserRoles;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.UserRolesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserRolesDao extends DAOImpl<UserRolesRecord, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles, UInteger> {

    /**
     * Create a new UserRolesDao without any configuration
     */
    public UserRolesDao() {
        super(UserRoles.USER_ROLES, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles.class);
    }

    /**
     * Create a new UserRolesDao with an attached configuration
     */
    @Autowired
    public UserRolesDao(Configuration configuration) {
        super(UserRoles.USER_ROLES, com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles> fetchById(UInteger... values) {
        return fetch(UserRoles.USER_ROLES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles fetchOneById(UInteger value) {
        return fetchOne(UserRoles.USER_ROLES.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles> fetchByUserId(UInteger... values) {
        return fetch(UserRoles.USER_ROLES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.torres999.sprintboot.shiro.dao.jooq.tables.pojos.UserRoles> fetchByRoleId(UInteger... values) {
        return fetch(UserRoles.USER_ROLES.ROLE_ID, values);
    }
}
