/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables;


import com.torres999.sprintboot.shiro.dao.jooq.Keys;
import com.torres999.sprintboot.shiro.dao.jooq.Shiro;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.RolesPermissionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesPermissions extends TableImpl<RolesPermissionsRecord> {

    private static final long serialVersionUID = -2039586768;

    /**
     * The reference instance of <code>shiro.roles_permissions</code>
     */
    public static final RolesPermissions ROLES_PERMISSIONS = new RolesPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RolesPermissionsRecord> getRecordType() {
        return RolesPermissionsRecord.class;
    }

    /**
     * The column <code>shiro.roles_permissions.id</code>.
     */
    public final TableField<RolesPermissionsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.roles_permissions.permission_id</code>.
     */
    public final TableField<RolesPermissionsRecord, UInteger> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.roles_permissions.role_id</code>.
     */
    public final TableField<RolesPermissionsRecord, UInteger> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>shiro.roles_permissions</code> table reference
     */
    public RolesPermissions() {
        this("roles_permissions", null);
    }

    /**
     * Create an aliased <code>shiro.roles_permissions</code> table reference
     */
    public RolesPermissions(String alias) {
        this(alias, ROLES_PERMISSIONS);
    }

    private RolesPermissions(String alias, Table<RolesPermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RolesPermissions(String alias, Table<RolesPermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shiro.SHIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RolesPermissionsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ROLES_PERMISSIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RolesPermissionsRecord> getPrimaryKey() {
        return Keys.KEY_ROLES_PERMISSIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RolesPermissionsRecord>> getKeys() {
        return Arrays.<UniqueKey<RolesPermissionsRecord>>asList(Keys.KEY_ROLES_PERMISSIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RolesPermissionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RolesPermissionsRecord, ?>>asList(Keys.PERMISSION_ID外键, Keys.ROLE_ID外键1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesPermissions as(String alias) {
        return new RolesPermissions(alias, this);
    }

    /**
     * Rename this table
     */
    public RolesPermissions rename(String name) {
        return new RolesPermissions(name, null);
    }
}
