/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables;


import com.torres999.sprintboot.shiro.dao.jooq.Keys;
import com.torres999.sprintboot.shiro.dao.jooq.Shiro;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9PermissionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T9Permission extends TableImpl<T9PermissionRecord> {

    private static final long serialVersionUID = -804730229;

    /**
     * The reference instance of <code>shiro.t9_permission</code>
     */
    public static final T9Permission T9_PERMISSION = new T9Permission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T9PermissionRecord> getRecordType() {
        return T9PermissionRecord.class;
    }

    /**
     * The column <code>shiro.t9_permission.permission_id</code>.
     */
    public final TableField<T9PermissionRecord, UInteger> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.t9_permission.permission_name</code>.
     */
    public final TableField<T9PermissionRecord, String> PERMISSION_NAME = createField("permission_name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>shiro.t9_permission.created_time</code>.
     */
    public final TableField<T9PermissionRecord, Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>shiro.t9_permission.update_time</code>.
     */
    public final TableField<T9PermissionRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>shiro.t9_permission</code> table reference
     */
    public T9Permission() {
        this("t9_permission", null);
    }

    /**
     * Create an aliased <code>shiro.t9_permission</code> table reference
     */
    public T9Permission(String alias) {
        this(alias, T9_PERMISSION);
    }

    private T9Permission(String alias, Table<T9PermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private T9Permission(String alias, Table<T9PermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shiro.SHIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<T9PermissionRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T9_PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T9PermissionRecord> getPrimaryKey() {
        return Keys.KEY_T9_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T9PermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<T9PermissionRecord>>asList(Keys.KEY_T9_PERMISSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9Permission as(String alias) {
        return new T9Permission(alias, this);
    }

    /**
     * Rename this table
     */
    public T9Permission rename(String name) {
        return new T9Permission(name, null);
    }
}
