/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables;


import com.torres999.sprintboot.shiro.dao.jooq.Keys;
import com.torres999.sprintboot.shiro.dao.jooq.Shiro;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9RolePermissionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T9RolePermission extends TableImpl<T9RolePermissionRecord> {

    private static final long serialVersionUID = 1096919153;

    /**
     * The reference instance of <code>shiro.t9_role_permission</code>
     */
    public static final T9RolePermission T9_ROLE_PERMISSION = new T9RolePermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T9RolePermissionRecord> getRecordType() {
        return T9RolePermissionRecord.class;
    }

    /**
     * The column <code>shiro.t9_role_permission.id</code>.
     */
    public final TableField<T9RolePermissionRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.t9_role_permission.permission_id</code>.
     */
    public final TableField<T9RolePermissionRecord, UInteger> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.t9_role_permission.role_id</code>.
     */
    public final TableField<T9RolePermissionRecord, UInteger> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>shiro.t9_role_permission</code> table reference
     */
    public T9RolePermission() {
        this("t9_role_permission", null);
    }

    /**
     * Create an aliased <code>shiro.t9_role_permission</code> table reference
     */
    public T9RolePermission(String alias) {
        this(alias, T9_ROLE_PERMISSION);
    }

    private T9RolePermission(String alias, Table<T9RolePermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private T9RolePermission(String alias, Table<T9RolePermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shiro.SHIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<T9RolePermissionRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T9_ROLE_PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T9RolePermissionRecord> getPrimaryKey() {
        return Keys.KEY_T9_ROLE_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T9RolePermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<T9RolePermissionRecord>>asList(Keys.KEY_T9_ROLE_PERMISSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9RolePermission as(String alias) {
        return new T9RolePermission(alias, this);
    }

    /**
     * Rename this table
     */
    public T9RolePermission rename(String name) {
        return new T9RolePermission(name, null);
    }
}
