/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables;


import com.torres999.sprintboot.shiro.dao.jooq.Keys;
import com.torres999.sprintboot.shiro.dao.jooq.Shiro;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9UserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T9User extends TableImpl<T9UserRecord> {

    private static final long serialVersionUID = 802244074;

    /**
     * The reference instance of <code>shiro.t9_user</code>
     */
    public static final T9User T9_USER = new T9User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T9UserRecord> getRecordType() {
        return T9UserRecord.class;
    }

    /**
     * The column <code>shiro.t9_user.user_id</code>.
     */
    public final TableField<T9UserRecord, UInteger> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.t9_user.username</code>.
     */
    public final TableField<T9UserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>shiro.t9_user.nickname</code>.
     */
    public final TableField<T9UserRecord, String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>shiro.t9_user.password</code>.
     */
    public final TableField<T9UserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>shiro.t9_user.status</code>.
     */
    public final TableField<T9UserRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

    /**
     * The column <code>shiro.t9_user.last_login_time</code>.
     */
    public final TableField<T9UserRecord, Timestamp> LAST_LOGIN_TIME = createField("last_login_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>shiro.t9_user.created_time</code>.
     */
    public final TableField<T9UserRecord, Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>shiro.t9_user.update_time</code>.
     */
    public final TableField<T9UserRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>shiro.t9_user</code> table reference
     */
    public T9User() {
        this("t9_user", null);
    }

    /**
     * Create an aliased <code>shiro.t9_user</code> table reference
     */
    public T9User(String alias) {
        this(alias, T9_USER);
    }

    private T9User(String alias, Table<T9UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private T9User(String alias, Table<T9UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shiro.SHIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<T9UserRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T9_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T9UserRecord> getPrimaryKey() {
        return Keys.KEY_T9_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T9UserRecord>> getKeys() {
        return Arrays.<UniqueKey<T9UserRecord>>asList(Keys.KEY_T9_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9User as(String alias) {
        return new T9User(alias, this);
    }

    /**
     * Rename this table
     */
    public T9User rename(String name) {
        return new T9User(name, null);
    }
}
