/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables;


import com.torres999.sprintboot.shiro.dao.jooq.Keys;
import com.torres999.sprintboot.shiro.dao.jooq.Shiro;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.UserRolesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends TableImpl<UserRolesRecord> {

    private static final long serialVersionUID = 308154785;

    /**
     * The reference instance of <code>shiro.user_roles</code>
     */
    public static final UserRoles USER_ROLES = new UserRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRolesRecord> getRecordType() {
        return UserRolesRecord.class;
    }

    /**
     * The column <code>shiro.user_roles.id</code>.
     */
    public final TableField<UserRolesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>shiro.user_roles.user_id</code>.
     */
    public final TableField<UserRolesRecord, UInteger> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>shiro.user_roles.role_id</code>.
     */
    public final TableField<UserRolesRecord, UInteger> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * Create a <code>shiro.user_roles</code> table reference
     */
    public UserRoles() {
        this("user_roles", null);
    }

    /**
     * Create an aliased <code>shiro.user_roles</code> table reference
     */
    public UserRoles(String alias) {
        this(alias, USER_ROLES);
    }

    private UserRoles(String alias, Table<UserRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserRoles(String alias, Table<UserRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Shiro.SHIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserRolesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_USER_ROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserRolesRecord> getPrimaryKey() {
        return Keys.KEY_USER_ROLES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserRolesRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRolesRecord>>asList(Keys.KEY_USER_ROLES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserRolesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserRolesRecord, ?>>asList(Keys.USER_ID外键, Keys.ROLE_ID外键);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRoles as(String alias) {
        return new UserRoles(alias, this);
    }

    /**
     * Rename this table
     */
    public UserRoles rename(String name) {
        return new UserRoles(name, null);
    }
}
