/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.records;


import com.torres999.sprintboot.shiro.dao.jooq.tables.GirlEntity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GirlEntityRecord extends UpdatableRecordImpl<GirlEntityRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = -932608210;

    /**
     * Setter for <code>shiro.girl_entity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>shiro.girl_entity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>shiro.girl_entity.age</code>.
     */
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>shiro.girl_entity.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>shiro.girl_entity.cup_size</code>.
     */
    public void setCupSize(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>shiro.girl_entity.cup_size</code>.
     */
    public String getCupSize() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GirlEntity.GIRL_ENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GirlEntity.GIRL_ENTITY.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GirlEntity.GIRL_ENTITY.CUP_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCupSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GirlEntityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GirlEntityRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GirlEntityRecord value3(String value) {
        setCupSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GirlEntityRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GirlEntityRecord
     */
    public GirlEntityRecord() {
        super(GirlEntity.GIRL_ENTITY);
    }

    /**
     * Create a detached, initialised GirlEntityRecord
     */
    public GirlEntityRecord(Integer id, Integer age, String cupSize) {
        super(GirlEntity.GIRL_ENTITY);

        set(0, id);
        set(1, age);
        set(2, cupSize);
    }
}
