/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.records;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Permission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionRecord extends UpdatableRecordImpl<PermissionRecord> implements Record4<UInteger, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1680887185;

    /**
     * Setter for <code>shiro.permission.permission_id</code>.
     */
    public void setPermissionId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>shiro.permission.permission_id</code>.
     */
    public UInteger getPermissionId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>shiro.permission.permission_name</code>.
     */
    public void setPermissionName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>shiro.permission.permission_name</code>.
     */
    public String getPermissionName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>shiro.permission.created_time</code>.
     */
    public void setCreatedTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>shiro.permission.created_time</code>.
     */
    public Timestamp getCreatedTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>shiro.permission.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>shiro.permission.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Permission.PERMISSION.PERMISSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Permission.PERMISSION.PERMISSION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Permission.PERMISSION.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Permission.PERMISSION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getPermissionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPermissionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value1(UInteger value) {
        setPermissionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value2(String value) {
        setPermissionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value3(Timestamp value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord values(UInteger value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionRecord
     */
    public PermissionRecord() {
        super(Permission.PERMISSION);
    }

    /**
     * Create a detached, initialised PermissionRecord
     */
    public PermissionRecord(UInteger permissionId, String permissionName, Timestamp createdTime, Timestamp updateTime) {
        super(Permission.PERMISSION);

        set(0, permissionId);
        set(1, permissionName);
        set(2, createdTime);
        set(3, updateTime);
    }
}
