/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.records;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T9RolePermissionRecord extends UpdatableRecordImpl<T9RolePermissionRecord> implements Record3<UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 984734808;

    /**
     * Setter for <code>shiro.t9_role_permission.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>shiro.t9_role_permission.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>shiro.t9_role_permission.permission_id</code>.
     */
    public void setPermissionId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>shiro.t9_role_permission.permission_id</code>.
     */
    public UInteger getPermissionId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>shiro.t9_role_permission.role_id</code>.
     */
    public void setRoleId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>shiro.t9_role_permission.role_id</code>.
     */
    public UInteger getRoleId() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return T9RolePermission.T9_ROLE_PERMISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return T9RolePermission.T9_ROLE_PERMISSION.PERMISSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return T9RolePermission.T9_ROLE_PERMISSION.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getPermissionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9RolePermissionRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9RolePermissionRecord value2(UInteger value) {
        setPermissionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9RolePermissionRecord value3(UInteger value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T9RolePermissionRecord values(UInteger value1, UInteger value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T9RolePermissionRecord
     */
    public T9RolePermissionRecord() {
        super(T9RolePermission.T9_ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised T9RolePermissionRecord
     */
    public T9RolePermissionRecord(UInteger id, UInteger permissionId, UInteger roleId) {
        super(T9RolePermission.T9_ROLE_PERMISSION);

        set(0, id);
        set(1, permissionId);
        set(2, roleId);
    }
}
