/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Author;
import com.torres999.sprintboot.shiro.dao.jooq.tables.Book;
import com.torres999.sprintboot.shiro.dao.jooq.tables.GirlEntity;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.AuthorRecord;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.BookRecord;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.GirlEntityRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>shiro</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthorRecord, Integer> IDENTITY_AUTHOR = Identities0.IDENTITY_AUTHOR;
    public static final Identity<GirlEntityRecord, Integer> IDENTITY_GIRL_ENTITY = Identities0.IDENTITY_GIRL_ENTITY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> KEY_AUTHOR_PRIMARY = UniqueKeys0.KEY_AUTHOR_PRIMARY;
    public static final UniqueKey<BookRecord> KEY_BOOK_PRIMARY = UniqueKeys0.KEY_BOOK_PRIMARY;
    public static final UniqueKey<GirlEntityRecord> KEY_GIRL_ENTITY_PRIMARY = UniqueKeys0.KEY_GIRL_ENTITY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AuthorRecord, Integer> IDENTITY_AUTHOR = createIdentity(Author.AUTHOR, Author.AUTHOR.ID);
        public static Identity<GirlEntityRecord, Integer> IDENTITY_GIRL_ENTITY = createIdentity(GirlEntity.GIRL_ENTITY, GirlEntity.GIRL_ENTITY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuthorRecord> KEY_AUTHOR_PRIMARY = createUniqueKey(Author.AUTHOR, "KEY_author_PRIMARY", Author.AUTHOR.ID);
        public static final UniqueKey<BookRecord> KEY_BOOK_PRIMARY = createUniqueKey(Book.BOOK, "KEY_book_PRIMARY", Book.BOOK.ID);
        public static final UniqueKey<GirlEntityRecord> KEY_GIRL_ENTITY_PRIMARY = createUniqueKey(GirlEntity.GIRL_ENTITY, "KEY_girl_entity_PRIMARY", GirlEntity.GIRL_ENTITY.ID);
    }
}
