/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9User;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9UserRole;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9PermissionRecord;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9RolePermissionRecord;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9RoleRecord;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9UserRecord;
import com.torres999.sprintboot.shiro.dao.jooq.tables.records.T9UserRoleRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships between tables of the <code>shiro</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<T9PermissionRecord, UInteger> IDENTITY_T9_PERMISSION = Identities0.IDENTITY_T9_PERMISSION;
    public static final Identity<T9RoleRecord, UInteger> IDENTITY_T9_ROLE = Identities0.IDENTITY_T9_ROLE;
    public static final Identity<T9RolePermissionRecord, UInteger> IDENTITY_T9_ROLE_PERMISSION = Identities0.IDENTITY_T9_ROLE_PERMISSION;
    public static final Identity<T9UserRecord, UInteger> IDENTITY_T9_USER = Identities0.IDENTITY_T9_USER;
    public static final Identity<T9UserRoleRecord, UInteger> IDENTITY_T9_USER_ROLE = Identities0.IDENTITY_T9_USER_ROLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<T9PermissionRecord> KEY_T9_PERMISSION_PRIMARY = UniqueKeys0.KEY_T9_PERMISSION_PRIMARY;
    public static final UniqueKey<T9RoleRecord> KEY_T9_ROLE_PRIMARY = UniqueKeys0.KEY_T9_ROLE_PRIMARY;
    public static final UniqueKey<T9RolePermissionRecord> KEY_T9_ROLE_PERMISSION_PRIMARY = UniqueKeys0.KEY_T9_ROLE_PERMISSION_PRIMARY;
    public static final UniqueKey<T9UserRecord> KEY_T9_USER_PRIMARY = UniqueKeys0.KEY_T9_USER_PRIMARY;
    public static final UniqueKey<T9UserRoleRecord> KEY_T9_USER_ROLE_PRIMARY = UniqueKeys0.KEY_T9_USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<T9PermissionRecord, UInteger> IDENTITY_T9_PERMISSION = createIdentity(T9Permission.T9_PERMISSION, T9Permission.T9_PERMISSION.PERMISSION_ID);
        public static Identity<T9RoleRecord, UInteger> IDENTITY_T9_ROLE = createIdentity(T9Role.T9_ROLE, T9Role.T9_ROLE.ROLE_ID);
        public static Identity<T9RolePermissionRecord, UInteger> IDENTITY_T9_ROLE_PERMISSION = createIdentity(T9RolePermission.T9_ROLE_PERMISSION, T9RolePermission.T9_ROLE_PERMISSION.ID);
        public static Identity<T9UserRecord, UInteger> IDENTITY_T9_USER = createIdentity(T9User.T9_USER, T9User.T9_USER.USER_ID);
        public static Identity<T9UserRoleRecord, UInteger> IDENTITY_T9_USER_ROLE = createIdentity(T9UserRole.T9_USER_ROLE, T9UserRole.T9_USER_ROLE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<T9PermissionRecord> KEY_T9_PERMISSION_PRIMARY = createUniqueKey(T9Permission.T9_PERMISSION, "KEY_t9_permission_PRIMARY", T9Permission.T9_PERMISSION.PERMISSION_ID);
        public static final UniqueKey<T9RoleRecord> KEY_T9_ROLE_PRIMARY = createUniqueKey(T9Role.T9_ROLE, "KEY_t9_role_PRIMARY", T9Role.T9_ROLE.ROLE_ID);
        public static final UniqueKey<T9RolePermissionRecord> KEY_T9_ROLE_PERMISSION_PRIMARY = createUniqueKey(T9RolePermission.T9_ROLE_PERMISSION, "KEY_t9_role_permission_PRIMARY", T9RolePermission.T9_ROLE_PERMISSION.ID);
        public static final UniqueKey<T9UserRecord> KEY_T9_USER_PRIMARY = createUniqueKey(T9User.T9_USER, "KEY_t9_user_PRIMARY", T9User.T9_USER.USER_ID);
        public static final UniqueKey<T9UserRoleRecord> KEY_T9_USER_ROLE_PRIMARY = createUniqueKey(T9UserRole.T9_USER_ROLE, "KEY_t9_user_role_PRIMARY", T9UserRole.T9_USER_ROLE.ID);
    }
}
