/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.RolesPermissions;
import com.torres999.sprintboot.shiro.dao.jooq.tables.UserRoles;
import com.torres999.sprintboot.shiro.dao.jooq.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shiro extends SchemaImpl {

    private static final long serialVersionUID = 2132001396;

    /**
     * The reference instance of <code>shiro</code>
     */
    public static final Shiro SHIRO = new Shiro();

    /**
     * The table <code>shiro.permission</code>.
     */
    public final Permission PERMISSION = com.torres999.sprintboot.shiro.dao.jooq.tables.Permission.PERMISSION;

    /**
     * The table <code>shiro.role</code>.
     */
    public final Role ROLE = com.torres999.sprintboot.shiro.dao.jooq.tables.Role.ROLE;

    /**
     * The table <code>shiro.roles_permissions</code>.
     */
    public final RolesPermissions ROLES_PERMISSIONS = com.torres999.sprintboot.shiro.dao.jooq.tables.RolesPermissions.ROLES_PERMISSIONS;

    /**
     * The table <code>shiro.users</code>.
     */
    public final Users USERS = com.torres999.sprintboot.shiro.dao.jooq.tables.Users.USERS;

    /**
     * The table <code>shiro.user_roles</code>.
     */
    public final UserRoles USER_ROLES = com.torres999.sprintboot.shiro.dao.jooq.tables.UserRoles.USER_ROLES;

    /**
     * No further instances allowed
     */
    private Shiro() {
        super("shiro", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Permission.PERMISSION,
            Role.ROLE,
            RolesPermissions.ROLES_PERMISSIONS,
            Users.USERS,
            UserRoles.USER_ROLES);
    }
}
