/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9User;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9UserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shiro extends SchemaImpl {

    private static final long serialVersionUID = -67527512;

    /**
     * The reference instance of <code>shiro</code>
     */
    public static final Shiro SHIRO = new Shiro();

    /**
     * The table <code>shiro.t9_permission</code>.
     */
    public final T9Permission T9_PERMISSION = com.torres999.sprintboot.shiro.dao.jooq.tables.T9Permission.T9_PERMISSION;

    /**
     * The table <code>shiro.t9_role</code>.
     */
    public final T9Role T9_ROLE = com.torres999.sprintboot.shiro.dao.jooq.tables.T9Role.T9_ROLE;

    /**
     * The table <code>shiro.t9_role_permission</code>.
     */
    public final T9RolePermission T9_ROLE_PERMISSION = com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission.T9_ROLE_PERMISSION;

    /**
     * The table <code>shiro.t9_user</code>.
     */
    public final T9User T9_USER = com.torres999.sprintboot.shiro.dao.jooq.tables.T9User.T9_USER;

    /**
     * The table <code>shiro.t9_user_role</code>.
     */
    public final T9UserRole T9_USER_ROLE = com.torres999.sprintboot.shiro.dao.jooq.tables.T9UserRole.T9_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Shiro() {
        super("shiro", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            T9Permission.T9_PERMISSION,
            T9Role.T9_ROLE,
            T9RolePermission.T9_ROLE_PERMISSION,
            T9User.T9_USER,
            T9UserRole.T9_USER_ROLE);
    }
}
