/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9User;
import com.torres999.sprintboot.shiro.dao.jooq.tables.T9UserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in shiro
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>shiro.t9_permission</code>.
     */
    public static final T9Permission T9_PERMISSION = com.torres999.sprintboot.shiro.dao.jooq.tables.T9Permission.T9_PERMISSION;

    /**
     * The table <code>shiro.t9_role</code>.
     */
    public static final T9Role T9_ROLE = com.torres999.sprintboot.shiro.dao.jooq.tables.T9Role.T9_ROLE;

    /**
     * The table <code>shiro.t9_role_permission</code>.
     */
    public static final T9RolePermission T9_ROLE_PERMISSION = com.torres999.sprintboot.shiro.dao.jooq.tables.T9RolePermission.T9_ROLE_PERMISSION;

    /**
     * The table <code>shiro.t9_user</code>.
     */
    public static final T9User T9_USER = com.torres999.sprintboot.shiro.dao.jooq.tables.T9User.T9_USER;

    /**
     * The table <code>shiro.t9_user_role</code>.
     */
    public static final T9UserRole T9_USER_ROLE = com.torres999.sprintboot.shiro.dao.jooq.tables.T9UserRole.T9_USER_ROLE;
}
