/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Author;
import com.torres999.sprintboot.shiro.dao.jooq.tables.Book;
import com.torres999.sprintboot.shiro.dao.jooq.tables.GirlEntity;
import com.torres999.sprintboot.shiro.dao.jooq.tables.TestIdx;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in shiro
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>shiro.author</code>.
     */
    public static final Author AUTHOR = com.torres999.sprintboot.shiro.dao.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>shiro.book</code>.
     */
    public static final Book BOOK = com.torres999.sprintboot.shiro.dao.jooq.tables.Book.BOOK;

    /**
     * The table <code>shiro.girl_entity</code>.
     */
    public static final GirlEntity GIRL_ENTITY = com.torres999.sprintboot.shiro.dao.jooq.tables.GirlEntity.GIRL_ENTITY;

    /**
     * test table
     */
    public static final TestIdx TEST_IDX = com.torres999.sprintboot.shiro.dao.jooq.tables.TestIdx.TEST_IDX;
}
