/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq;


import com.torres999.sprintboot.shiro.dao.jooq.tables.Permission;
import com.torres999.sprintboot.shiro.dao.jooq.tables.Role;
import com.torres999.sprintboot.shiro.dao.jooq.tables.RolesPermissions;
import com.torres999.sprintboot.shiro.dao.jooq.tables.UserRoles;
import com.torres999.sprintboot.shiro.dao.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in shiro
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>shiro.permission</code>.
     */
    public static final Permission PERMISSION = com.torres999.sprintboot.shiro.dao.jooq.tables.Permission.PERMISSION;

    /**
     * The table <code>shiro.role</code>.
     */
    public static final Role ROLE = com.torres999.sprintboot.shiro.dao.jooq.tables.Role.ROLE;

    /**
     * The table <code>shiro.roles_permissions</code>.
     */
    public static final RolesPermissions ROLES_PERMISSIONS = com.torres999.sprintboot.shiro.dao.jooq.tables.RolesPermissions.ROLES_PERMISSIONS;

    /**
     * The table <code>shiro.users</code>.
     */
    public static final Users USERS = com.torres999.sprintboot.shiro.dao.jooq.tables.Users.USERS;

    /**
     * The table <code>shiro.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = com.torres999.sprintboot.shiro.dao.jooq.tables.UserRoles.USER_ROLES;
}
