/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GirlEntity implements Serializable {

    private static final long serialVersionUID = -411470422;

    private Integer id;
    private Integer age;
    private String  cupSize;

    public GirlEntity() {}

    public GirlEntity(GirlEntity value) {
        this.id = value.id;
        this.age = value.age;
        this.cupSize = value.cupSize;
    }

    public GirlEntity(
        Integer id,
        Integer age,
        String  cupSize
    ) {
        this.id = id;
        this.age = age;
        this.cupSize = cupSize;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getCupSize() {
        return this.cupSize;
    }

    public void setCupSize(String cupSize) {
        this.cupSize = cupSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GirlEntity (");

        sb.append(id);
        sb.append(", ").append(age);
        sb.append(", ").append(cupSize);

        sb.append(")");
        return sb.toString();
    }
}
