/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = -653794613;

    private UInteger  roleId;
    private String    roleName;
    private Timestamp createdTime;
    private Timestamp updateTime;

    public Role() {}

    public Role(Role value) {
        this.roleId = value.roleId;
        this.roleName = value.roleName;
        this.createdTime = value.createdTime;
        this.updateTime = value.updateTime;
    }

    public Role(
        UInteger  roleId,
        String    roleName,
        Timestamp createdTime,
        Timestamp updateTime
    ) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
    }

    public UInteger getRoleId() {
        return this.roleId;
    }

    public void setRoleId(UInteger roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(roleId);
        sb.append(", ").append(roleName);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
