/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T9Permission implements Serializable {

    private static final long serialVersionUID = 185827065;

    private UInteger  permissionId;
    private String    permissionName;
    private Timestamp createdTime;
    private Timestamp updateTime;

    public T9Permission() {}

    public T9Permission(T9Permission value) {
        this.permissionId = value.permissionId;
        this.permissionName = value.permissionName;
        this.createdTime = value.createdTime;
        this.updateTime = value.updateTime;
    }

    public T9Permission(
        UInteger  permissionId,
        String    permissionName,
        Timestamp createdTime,
        Timestamp updateTime
    ) {
        this.permissionId = permissionId;
        this.permissionName = permissionName;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
    }

    public UInteger getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(UInteger permissionId) {
        this.permissionId = permissionId;
    }

    public String getPermissionName() {
        return this.permissionName;
    }

    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("T9Permission (");

        sb.append(permissionId);
        sb.append(", ").append(permissionName);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
