/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 400335640;

    private UInteger  userId;
    private String    userName;
    private String    password;
    private Timestamp createdTime;
    private Timestamp updateTime;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.password = value.password;
        this.createdTime = value.createdTime;
        this.updateTime = value.updateTime;
    }

    public Users(
        UInteger  userId,
        String    userName,
        String    password,
        Timestamp createdTime,
        Timestamp updateTime
    ) {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
    }

    public UInteger getUserId() {
        return this.userId;
    }

    public void setUserId(UInteger userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
