/**
 * This class is generated by jOOQ
 */
package com.torres999.sprintboot.shiro.dao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles implements Serializable {

    private static final long serialVersionUID = -804665142;

    private UInteger id;
    private UInteger userId;
    private UInteger roleId;

    public UserRoles() {}

    public UserRoles(UserRoles value) {
        this.id = value.id;
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public UserRoles(
        UInteger id,
        UInteger userId,
        UInteger roleId
    ) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UInteger getUserId() {
        return this.userId;
    }

    public void setUserId(UInteger userId) {
        this.userId = userId;
    }

    public UInteger getRoleId() {
        return this.roleId;
    }

    public void setRoleId(UInteger roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRoles (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
